alpha-blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root 'pages#home'
get 'about', to: 'pages#about'

resources :articles

get 'signup', to: 'users#new'
resources :users, except: [:new]

get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

end

alpha-blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

alpha-blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 } # it ensures title is not null, means title required
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

alpha-blog/app/models/user.rb
class User < ApplicationRecord 
    has_many :articles, dependent: :destroy # if the destroyed, delete all articles
    before_save { self.email = email.downcase }
    validates :username, presence: true,
                uniqueness: { case_sensitive: false },
                length: { minimum: 3, maximum: 25 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i # email regular expression
    validates :email, presence: true, length: { maximum: 105 },
                uniqueness: { case_sensitive: false },
                format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user # if we have a current user it will return true
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end
end

alpha-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end
   
    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user # this will fixed
        if @article.save
            flash[:success] = "Article was successfully created!"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def update
        if @article.update(article_params)
            flash[:success] = "Article was successfully updated"
            redirect_to article_path(@article)
        else
            render "edit"
        end
    end

    def show
    end

    def destroy
        @article.destroy
        flash[:danger] = "Article was successfully deleted"
        redirect_to articles_path
    end

    private
    def article_params
        params.require(:article).permit(:title, :description)
    end

    def set_article
        @article = Article.find(params[:id])
    end

    def require_same_user
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "You can only edit or delete your own article"
            redirect_to root_path
        end
    end
end

alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
    end

    def about

    end

end

alpha-blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have succesfully logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login information"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have succesfully logged out"
        redirect_to root_path
    end

end

alpha-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 2)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all articles created by user have been deleted"
        redirect_to users_path
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end

    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "You need to be admin to perform that action"
            redirect_to root_path
        end
    end
end

alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
    end
end

alpha-blog/app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row justify-content-md-center">
    <div class="col-xl-8">
        <div class="card card-body bg-light">
            <div class="article-title">
                <%= link_to article.title, article_path(article) %>
            </div>
            <div class="article-body">
                <%= truncate(article.description, length: 100) %>
            </div>
            <div class="article-actions">
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete this article", article_path(article),
                                    method: :delete,
                                    data: { confirm: "Are you sure you want to delete the article?" },
                                    class: "btn btn-xs btn-danger" %>
                <% end %>
                <div class="article-meta-details">
                    <small>Created by: <%= link_to article.user.username, user_path(article.user) if article.user %>,
                        <%= time_ago_in_words(article.created_at) %> ago,
                        last updated: <%= time_ago_in_words(article.updated_at) %> ago
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

alpha-blog/app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class="col-xl-12">
        <%= form_for @article do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-12">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control label col-sm-2">
                    <%= f.label :description %><br/>
                </div>
                <div class="col-sm-12">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-12">
                    <%= f.submit class: "btn btn-primary btn-lg btn-dark" %>
                </div>
            </div>
        <% end %>
        <div class = "col-xl-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>
    </div>
</div>

alpha-blog/app/views/articles/edit.html.erb
<h1 align = "center">Edit Article</h1>

<%= render 'form' %>

alpha-blog/app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<div class="d-flex align-items-center justify-content-center ">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div class="d-flex align-items-center justify-content-center ">
  <%= will_paginate %>
</div>

alpha-blog/app/views/articles/new.html.erb
<h1 align = "center">Create an article</h1>

<%= render 'form' %>

alpha-blog/app/views/articles/show.html.erb
<h2 align="center">
  Title: <%= @article.title %>
</h2>
<div class="row justify-content-md-center">
  <div class="card card-body bg-light col-xl-8">
    <% if @article.user %>
      <div align="center">
        <ul class="listing">
            <div class="row justify-content-md-center">
              <div class="col-md-4">
                <li>Created by:</li>
                <li> <%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                <li class="article-title">
                <%= link_to @article.user.username, user_path(@article.user) %>
                </li>
                <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
              </div>
            </div>
          </ul>
        </div>
    <% end %>
    <h4 class = "center description"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>
    <div class="article-actions">
      <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete this article", article_path(@article),
                                            method: :delete,
                                            data: { confirm: "Are you sure you want to delete the article?" },
                                            class: "btn btn-xs btn-danger" %>
      <% end %>
      <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
    </div> 
  </div>
</div>

alpha-blog/app/views/layouts/_footer.html.erb
<div class = "container">
  <footer class="footer">
    <small>
     Copyright &copy; by <a href = "https://www.ridvantulemen.com"> Ridvan Tulemen
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

alpha-blog/app/views/layouts/_messages.html.erb
<div class="row justify-content-md-center">
  <div class="col col-xl-10">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

alpha-blog/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><%= link_to "Articles", articles_path, class:"nav-link" %></li>
            <li class="nav-item"><%= link_to "Users", users_path, class:"nav-link" %></li>

            <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Actions
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <!--<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>-->
            <ul class="navbar-nav">
                <% if logged_in? %>
                <li class="nav-item">
                    <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Your Profile <%= "Admin" if current_user.admin? %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
                        <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to 'Log in', login_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign up', signup_path, class: "nav-link" %>
                </li>
                <% end %>
            </ul>
        </form>
    </div>
</nav>

alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

alpha-blog/app/views/pages/about.html.erb
<h1> This is about page </h1>

<%= link_to 'About', root_path %>

alpha-blog/app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1 class="display-3 font-weight-bold" >ALPHA BLOG</h1>
  <%= link_to "Sign up now", signup_path, class: "btn btn-dark btn-lg" %> 
</div>

alpha-blog/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row justify-content-md-center">
        <div class="col-10">
            <div class="card text-white bg-danger mb-3">
                <div class="card-header">
                    <h2 class="card-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this article from being saved:
                    </h2>
                    <div class="card-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

alpha-blog/app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
    <div class="col-xl-12">
        <%= form_for @user do |f| %>
            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :username %>
                </div>
                <div class="col-sm-10">
                    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
                </div>
            </div>
            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :email %><br/>
                </div>
                <div class="col-sm-10">
                    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
                </div>
            </div>
            <div class="form-group row">
                <div class="control-label col-sm-2">
                    <%= f.label :password %><br/>
                </div>
                <div class="col-sm-10">
                    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg") %>
                </div>
            </div>
        <% end %>
        <div class = "col-xl-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>
    </div>
</div>

alpha-blog/app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

alpha-blog/app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>

<div class="center">
<div class="d-flex align-items-center justify-content-center ">
  <%= will_paginate %>
</div>
  <% @users.each do |user| %>
    <ul class="listing">
        <div class="row justify-content-md-center">
          <div class="card card-body bg-light col-md-4">
            <li> <%= link_to gravatar_for(user), user_path(user) %></li>
            <li class="article-title">
            <%= link_to user.username, user_path(user) %>
            </li>
            <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
            <% if logged_in? and current_user.admin? %>
              <li> <%= link_to "Delete this user", user_path(user), method: :delete,
                        data: { confirm: "Are you sure you want the delete the user and all the articles" },
                        class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
    </ul>
  <% end %>
<div class="d-flex align-items-center justify-content-center ">
  <%= will_paginate %>
</div>
</div>

alpha-blog/app/views/users/new.html.erb
<h1 align="center">Signup for Alpha Blog</h1>

<%= render 'form' %>

alpha-blog/app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row justify-content-md-center">
  <div class="col-md-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<h4 align="center"><%= @user.username %>'s articles</h4>

<div class="d-flex align-items-center justify-content-center ">
  <%= will_paginate @user_articles %>
</div>

<%= render '/articles/article', obj: @user_articles %>

<div class="d-flex align-items-center justify-content-center ">
  <%= will_paginate @user_articles %>
</div>